version: "3.3"
services:
  tr-benchmark-${TAG}:
    image: ${REGISTRY_ADDRESS}/tr-benchmark:${TAG}
    build:
      dockerfile: ./benchy.dockerfile
      args:
        FILE_SIZE: ${FILE_SIZE}
        N_FILES: ${N_FILES}
